### PR TITLE
GENERATE CERTIFICATE FINGERPRINT IN GO

### LINKED ISSUE #132: Generate certificate fingerprint in Go
[dtls_tlscfg_fingerprint](https://github.com/pions/webrtc/blob/master/internal/dtls/dtls.c#L334) can easily be done in Go

### PR DESCRIPTION
**Pull request by aguilEA**
Implement dtls_tlscfg_fingerprint in Go.

Resolves #132

### CODE REVIEW

**Comment by Sean-Der** [comment]
Nice work, thank you for taking this on @aguilEA !

Can you delete the code from the `.h` and `.c` files that did this before? Also I would delete the new `dtlsTlscfgFingerprint` function and just move everything inside `Fingerprint` function.

**Comment by aguilEA** [comment]
No problem. I will make those changes in the new commit.

**Comment by Sean-Der** [comment]
Hey @aguilEA commit msg+code LGTM!

Would you mind undoing the deletion of 
```
internal/network/manager.go
internal/network/port-send.go
internal/stun/stun.go
pkg/ice/agent.go
pkg/ice/candidate.go
pkg/ice/url.go
```

and we should be good

**Comment by aguilEA** [comment]
No problem I made a mistake trying to only see the files I had modified. I
will undo the changes.

**Comment by aguilEA** [comment]
I submitted the commit with the files back on.  I continue to get the
commit message error 'Limit the subject line to 50 characters'.  There is a
single commit and the commit message is formatted according to the rules.
Let me know if there is something I need to do to fix the error.

Thanks,
Earle

**Comment by Sean-Der** [comment]
@aguilEA that is for an old commit (and your behind master) sorry about that!

I think your commit is good to go! Let me test it out locally, and should be able to merge it tonight :) thank you for contributing

**Comment by aguilEA** [comment]
Awesome!
No problem, Im really interested in WebRTC and rewriting it in Go seems
like great idea.
Im glad I could help.

**Comment by Sean-Der** [comment]
Thanks for the contribution @aguilEA sorry it took so long to merge! It has been a lot of fun writing it in Go, and hopefully we can make some great stuff in the future with it :)

**Pull request merged**
