### PR TITLE
[WIP] ORTC Media API Refinements

### PR DESCRIPTION
**Pull request by backkem**
Goals:
- Split SDP parsing from network setup, based on [webrtcHacks/adapter](github.com/webrtcHacks/adapter).
- Move SRTP specific logic to SRTP package.
- Move ORTC Media API constructors to the API object.
- Minor API cleanup

TODO:
- [ ] Fix tests
- [ ] Update go.mod for DTLS & SRTP dependencies.

### CODE REVIEW

**Comment by backkem** [comment]
Yikes, that's a lot of conflicts :/ I'll see if I can save this PR since there is still a lot of good stuff in there, I think.

**Comment by Sean-Der** [comment]
Hey @backkem sorry I keep causing churn to break this :(

Wanna work together and get this all in?

**Comment by backkem** [comment]
> Wanna work together and get this all in?

Yea, definitely still interested in getting this in at some point.

**Comment by Sean-Der** [comment]
I am going to start plucking changes from this branch, closing PR for now

**Pull request closed without merging**
